import { queryKeys } from './queryKeys'

describe('query keys', () => {
  it('produces stable keys', () => {
    expect(queryKeys.knowledgeBases()).toEqual(['knowledge-bases'])
    expect(queryKeys.knowledgeBase('kb')).toEqual(['knowledge-bases', 'kb'])
    expect(queryKeys.knowledgeBaseActiveAiProfile('kb')).toEqual(['knowledge-bases', 'kb', 'active-ai-profile'])
    expect(queryKeys.runtimeSettings()).toEqual(['runtime-settings'])
    expect(queryKeys.aiProfiles()).toEqual(['ai-profiles'])
    expect(queryKeys.aiProfile('profile-1')).toEqual(['ai-profiles', 'profile-1'])
    expect(queryKeys.schemasByKnowledgeBase('kb-1')).toEqual(['schemas', 'knowledge-base', 'kb-1'])
    expect(queryKeys.schemasByKnowledgeBaseMaybe('kb-1')).toEqual(['schemas', 'knowledge-base', 'kb-1'])
    expect(queryKeys.schemasByKnowledgeBaseMaybe(null)).toEqual(['schemas', 'knowledge-base', 'none'])
    expect(queryKeys.schemaLookup('schema-1')).toEqual(['schemas', 'lookup', 'schema-1'])
    expect(queryKeys.documents('kb-1')).toEqual(['documents', 'knowledge-base', 'kb-1'])
    expect(queryKeys.documentsMaybe('kb-1')).toEqual(['documents', 'knowledge-base', 'kb-1'])
    expect(queryKeys.documentsMaybe(null)).toEqual(['documents', 'knowledge-base', 'none'])
    expect(queryKeys.chunks('doc-1')).toEqual(['documents', 'chunks', 'doc-1'])
    expect(queryKeys.chunksMaybe('doc-1')).toEqual(['documents', 'chunks', 'doc-1'])
    expect(queryKeys.chunksMaybe(null)).toEqual(['documents', 'chunks', 'none'])
    expect(queryKeys.documentProcessingOptions('doc-1')).toEqual(['documents', 'processing-options', 'doc-1'])
    expect(queryKeys.documentProcessingOptionsMaybe('doc-1')).toEqual(['documents', 'processing-options', 'doc-1'])
    expect(queryKeys.documentProcessingOptionsMaybe(null)).toEqual(['documents', 'processing-options', 'none'])
  })
})
